#!/usr/bin/env bash
#Web servers are the piece of software generating and serving
# HTML pages, let’s install one!
apt-get -y update
apt-get -y install nginx
# Start nginx if it's not already running
service nginx start

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Serve "Hello World!" at the root endpoint
echo "Hello World!" | sudo tee  /var/www/html/index.html
service nginx restart
