#!/usr/bin/env bash
# Install nginx if it's not already installed

if ! command -v nginx &> /dev/null; then
  apt-get -y update
  apt-get -y install nginx
fi

# Configure nginx to redirect /redirect_me to another page with a 301 Moved Permanently status code

sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx

service nginx restar
