#!/usr/bin/env bash
# Install nginx if it's not already installed

if ! command -v nginx &> /dev/null; then
  apt-get -y update
  apt-get -y install nginx
fi
service nginx start
# Configure nginx to redirect /redirect_me to another page with a 301 Moved Permanently status code

sed -i '/listen \[::\]:80 default_server;/a location = \/redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart nginx

service nginx restart
