#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure custom HTTP response header
echo 'add_header X-Served-By $hostname;' > /etc/nginx/conf.d/custom_headers.conf

# Restart Nginx
service nginx restart
